<<<<<<< HEAD
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
=======
>>>>>>> TEMPLATE
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::fastqc=0.12.1
