name: "assignment_heatmap"
description: Creates a likelihood heatmap for the taxonomic classification for all reads for each sample.
keywords:
  - emu
  - likelihood
  - R
tools:
  - assignment_heatmap.R:
    description: "In-house script for creating a simple heatmap."
    homepage: "-"
    documentation: "-"
input:
  # Abundance file
  - assignment_translated_report:
    type: file
    description: "Modified file (names instead of tax-id) from emu abundance that describes the likelihood for the taxonomic classification for each read."
    pattern: "*{read-assignment-distributions_translated.tsv}"
output:
  - assignment_heatmap:
    type: file
    description: a heatmap
    pattern: "*assignment_heatmap.png"
  - versions:
    type: file
    description: File containing software versions
    pattern: "versions.yml"
  - assignment_heatmap_log:
    type: file
    description: log
    pattern: "assignment_heatmap_log.log"

authors:
  - "@fwa93"
