name: "generate_input"
## TODO nf-core: Add a description of the module and list keywords
description: Produce a samplesheet for previously merged fastq-files
keywords:
  - fastq-concatenation
  - samplesheet-generation
  - Nanopore

tools:
  - "generate_input.sh":
      ## TODO nf-core: Add a description and other details for the software below
      description: "Produce a samplesheet for previously merged fastq-files"
      homepage: ""
      documentation: ""
      tool_dev_url: "None"
      doi: ""
      licence: "['MIT']"

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  #
  ## TODO nf-core: Delete / customise this example input
  - merged_files:
      type: file
      description: merged fastq.gz files
      pattern: "*.{fastq.gz}"

## TODO nf-core: Add a description of all of the variables used as output
output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  #
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  ## TODO nf-core: Delete / customise this example output
  - sample_sheet_merged:
      type: file
      description: A samplesheet containgin info about reads and sample names
      pattern: "*{amplesheet_merged.csv}"
  - generate_input_log:
      type: file
      description: log
      pattern: "*{.log}"

authors:
  - "@fwa93"
