name: CI
# This workflow runs the pipeline with the minimal test dataset to check that
# it completes without errors
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    draft: true
  release:
    types: [published]
  workflow_dispatch:

env:
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: "Run pipeline with test data (${{ matrix.NXF_VER }} | ${{ matrix.test_name }} | ${{ matrix.profile }})"
    # Only run on push if this is in the main repository
    if: "${{ github.repository_owner == 'genomic-medicine-sweden' }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "latest-everything"
        profile:
          - "conda"
          - "docker"
          - "singularity"
        test_name:
          - "test"
        is_master:
          - ${{ github.base_ref == 'main' }}
        # Exclude conda and singularity on dev
        exclude:
          - is_master: false
            profile: "conda"
          - is_master: false
            profile: "singularity"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1

      - name: Set up Apptainer
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-apptainer@main

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        run: |
          mkdir -p $NXF_SINGULARITY_CACHEDIR
          mkdir -p $NXF_SINGULARITY_LIBRARYDIR

      - name: Set up Miniconda
        if: matrix.profile == 'conda'
        uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          conda-solver: libmamba
          channels: conda-forge,bioconda

      - name: Set up Conda
        if: matrix.profile == 'conda'
        run: |
          echo $(realpath $CONDA)/condabin >> $GITHUB_PATH
          echo $(realpath python) >> $GITHUB_PATH

      - name: Clean up Disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Report disk-usage before make install
        run: df -h

      - name: Run Make install
        run: make install

      - name: Report disk-usage after make install
        run: df -h

      # Make sure we can run a full pipeline from the commandline as well
      - name: "Run pipeline from the commandline with merge fastq pass ${{ matrix.NXF_VER }} | ${{ matrix.test_name }} | ${{ matrix.profile }}"
        run: |
          nextflow  \
            -log $(pwd)/nextflow.log \
            run ${GITHUB_WORKSPACE} \
            -profile ${{ matrix.test_name}},${{ matrix.profile }} \
            --outdir results \
            --db $(pwd)/assets/databases/emu_database \
            --seqtype map-ont \
            --quality_filtering \
            --longread_qc_qualityfilter_minlength 1200 \
            --longread_qc_qualityfilter_maxlength 1800 \
            --merge_fastq_pass $(pwd)/assets/test_assets/ci

      - name: Run pipeline from the commandline with samplesheet
        run: |
          nextflow  \
            -log $(pwd)/nextflow.log \
            run main.nf \
            -profile ${{ matrix.test_name}},${{ matrix.profile }} \
            --outdir results \
            --db $(pwd)/assets/databases/emu_database \
            --seqtype map-ont \
            --quality_filtering \
            --longread_qc_qualityfilter_minlength 1200 \
            --longread_qc_qualityfilter_maxlength 1800 \
            --input https://raw.githubusercontent.com/genomic-medicine-sweden/test-datasets/refs/heads/16s/samplesheet.csv

      # Run via nf-test for more detailed checking
      - name: Run nf-test
        run: |
          nf-test test tests/main.nf.test
